### ISSUE TITLE
소프트웨어명 작명

### ISSUE THREAD

**Issue by tmdgh1592** [tmdgh1592/SE2022_3_3#1]
본인이 생각하는 소프트웨어명을 해당 이슈 하단에 작성해주세요.

**Comment by kms146594** [comment]
Case By Case(C.B.C , 케바케)
때에 따라 다르게, 계절에 따라 다르게
자신만의 태그를 찾아 나만의 옷장을 완성하다.

**Comment by wonmin98** [comment]
Hanger (옷걸이)
내 옷 ,내 손안에 걸어놓다

My closet manager - MCM
어플로 관리하는 나만의 옷장

**Comment by tmdgh1592** [comment]
WC - Weather Closet (계절 옷장)
계절에 따른 옷장 구분이 가능하다는 뜻입니다.

마이옷
언제든 내 옷을 한 번에 찾아본다.

**Comment by flirtheory3** [comment]
어쩔옷장
